[tool.pylint.messages_control]

disable = [
    "missing-function-docstring",
    "missing-class-docstring",
    "missing-module-docstring",
    "missing-final-newline",
    "too-many-arguments",
    "too-many-positional-arguments",
    "too-few-public-methods"
]

[tool.black]
skip-string-normalization=true
line-length=100