name: CI Tests
on:
  pull_request:
    branches:
      - "develop"
env:
  AWS_DEFAULT_REGION: "us-east-2"
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out project repo
        uses: actions/checkout@v2

      - name: Set up Python 3.13
        uses: actions/setup-python@v2
        with:
          python-version: 3.13

      - name: Install dependencies
        run: pip install --no-cache-dir -U pip && pip install --no-cache-dir -r requirements.txt

      - name: Lint code
        run: pylint .

      - name: Run unit tests
        run: pytest tests/

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Run integration tests
        run: integration_tests/run.sh

  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - name: Check out project repo
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Create Terraform plan
        id: tf_plan
        working-directory: "./infrastructure"
        run: terraform init -backend-config="key=mlops-environment-prod.tfstate" --reconfigure && terraform plan -var-file=vars/prod.tfvars
